"""Report generator for exporting research as Markdown files.

Takes research results and formats them into a nicely structured
Markdown document that can be saved and shared.
"""

import os
from datetime import datetime


def generate_report(query: str, answer: str, tools_used: list = None) -> str:
    """
    Generate a formatted Markdown research report.

    Args:
        query: The original research question
        answer: The agent's final answer
        tools_used: Optional list of tools that were used

    Returns:
        Formatted Markdown string
    """
    # Get current timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    date_only = datetime.now().strftime("%Y-%m-%d")

    # Build the report
    report = f"""# Research Report

**Date:** {timestamp}

---

## Research Question

{query}

---

## Findings

{answer}

---

## Methodology

This research was conducted using an AI-powered research agent with access to:
- **Web Search** - Current information from the internet
- **Wikipedia** - Encyclopedic background knowledge
- **Calculator** - Mathematical computations
- **Weather** - Real-time weather data
- **News Search** - Recent news articles
- **URL Fetcher** - Reading specific web pages

The agent autonomously decided which tools to use based on the question.

---

## About This Report

- **Generated by:** Multi-Tool Research Agent
- **AI Model:** Claude (Anthropic)
- **Framework:** LangChain with ReAct pattern

---

*This report was automatically generated. Please verify important information from primary sources.*
"""
    return report


def save_report(report: str, filename: str = None, output_dir: str = "output") -> str:
    """
    Save a report to a Markdown file.

    Args:
        report: The Markdown report content
        filename: Optional custom filename (without extension)
        output_dir: Directory to save reports (default: "output")

    Returns:
        The full path to the saved file
    """
    # Create output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Generate filename if not provided
    if filename is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"research_{timestamp}"

    # Ensure .md extension
    if not filename.endswith('.md'):
        filename += '.md'

    # Full path
    filepath = os.path.join(output_dir, filename)

    # Write the file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(report)

    return filepath


def export_research(query: str, answer: str, filename: str = None) -> str:
    """
    Convenience function: Generate and save a research report in one call.

    Args:
        query: The research question
        answer: The agent's answer
        filename: Optional custom filename

    Returns:
        Path to the saved report file
    """
    report = generate_report(query, answer)
    filepath = save_report(report, filename)
    return filepath
